### ISSUE TITLE
ModuleNotFoundError: No module named 'pynput'

### ISSUE THREAD

**Issue by vira-code** [ThisIsMatin/AdobeConnectFarsiType#1]
hi dear
why system show this error?
ModuleNotFoundError: No module named 'pynput'

**Comment by vira-code** [comment]
i am install all modules with pip

**Comment by ThisIsMatin** [comment]
Hi
Try installing the latest version of the pynput module using following command :
`python -m pip install pynput`
Also, a module used in this project is unfortunately not included in requirements.txt
This problem may also be due to this module
So try to install this module too :
`python -m pip install plyer==2.0.0`
